# Configure and start nginx
---
- name: 'Find notebook static directory'
  command: '{{ python_executable }} -c "import notebook; import os; print(os.path.join(notebook.__path__[0], \"static\"));"'
  register: notebook_static_directory

- name: 'Configure nginx'
  template: 
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
    backup: yes
  notify: 'reload nginx'

- name: 'Start the nginx service'
  service: 
    name: 'nginx'
    state: started
    enabled: yes
