# Install SSL cert/key using letsencrypt
---

- fail: msg="you must provide an email for usage with letsencrypt"
  when: use_letsencrypt and (letsencrypt_email == '' or letsencrypt_email is undefined)

- name: stop the nginx service
  service: name=nginx state=stopped enabled=yes
  become: true
  when: use_letsencrypt

- name: set apt-yes default (needed for certbot)
  lineinfile:
    dest: /etc/apt/apt.conf.d/99-apt-yes
    state: present
    line: 'APT::Get::Assume-Yes "true";'
    create: yes
  become: true
  when: use_letsencrypt

- name: install certbot (letsencrypt)
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/local/bin/certbot-auto
    mode: 755
  when: use_letsencrypt

- name: SSL credentials with certbot
  command: /usr/local/bin/certbot-auto certonly --agree-tos --standalone -m {{ letsencrypt_email }} -d {{ inventory_hostname }} creates={{ letsencrypt_ssl_cert_path }}
  become: true
  when: use_letsencrypt

- name: Setup letsencrypt renewal with cron
  copy: src=letsencrypt-renew dest=/etc/cron.daily/letsencrypt-renew mode=0755
  become: true
  when: use_letsencrypt