---
- name: 'Reload JupyterHub supervisor config'
  supervisorctl: 
    name: 'jupyterhub'
    state: present
  listen: 'reload jupyterhub'

- name: 'Restart JupyterHub with supervisor'
  supervisorctl: 
    name: 'jupyterhub'
    state: restarted
  listen: 'reload jupyterhub'